apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.deployment.name }}
  labels:
    app: nginx
spec:
  replicas: {{ .Values.deployment.replicas }}
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      volumes:
      - name: task-pv-storage
        persistentVolumeClaim:
          claimName: {{ .Values.deployment.claimName }}
      containers:
      - name: nginx
        image: {{ .Values.deployment.image }}:{{ .Values.deployment.tag }}
        ports:
        - containerPort: {{ .Values.deployment.containerPort }}
        volumeMounts:
        - name: task-pv-storage
          mountPath: {{ .Values.deployment.mountPath }}