deployment:
  name: nginx-deployment
  image: nginx
  tag: 1.14.2
  containerPort: 80
  replicas: 2
  claimName: task-pv-claim
  mountPath: /usr/share/nginx/html

pvc:
  name: task-pv-claim
  accessMode: ReadWriteOnce
  capacity: 10Gi
  storageClassName: standard