apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.deployment.name2 }}
  labels:
    app: nginx
spec:
  replicas: {{ .Values.deployment.replicas2 }}
  selector:
    matchLabels:
      app: nginx2
  template:
    metadata:
      labels:
        app: nginx2
    spec:
      containers:
      - name: nginx
        image: {{ .Values.deployment.name2_image.repository }}:{{ .Values.deployment.name2_image.tag }}

        ports:
        - containerPort: {{ .Values.deployment.containerPort2 }}
