apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name1 }}
spec:
  type: NodePort
  selector:
    app: nginx
  ports:
    - protocol: TCP
      port: 80
      targetPort: {{ .Values.service.targetPort1}}
      nodePort: 30002
