apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name2 }}
spec:
  type: NodePort
  selector:
    app: nginx2
  ports:
    - protocol: TCP
      port: 80
      targetPort: {{ .Values.service.targetPort2}}
      nodePort: 30003
